version: '3'
services:
    app:
        build: ./
        ports:
            - "3000:3000"
            - "20002:20002"
        volumes:
            - .:/app
            - ~/.aws/:/root/.aws/
        tty: true
        command: "npm run dev"
